import './globals.css'
import 'react-day-picker/dist/style.css'
import type {Metadata} from 'next'
import localFont from "next/font/local";
import {Providers} from "@/redux/provider";
import {WagmiAppConfig} from "@/components/layout/WagmiAppConfig";

const helvetica = localFont({
  src: [
    {
      path: './fonts/regular.woff',
      weight: '400',
      style: 'normal'
    },
    {
      path: './fonts/medium.woff',
      weight: '500',
      style: 'normal'
    },
    {
      path: './fonts/mediumItalic.woff',
      weight: '500',
      style: 'italic'
    },
    {
      path: './fonts/bold.woff',
      weight: '700',
      style: 'normal'
    },
  ]
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body className={helvetica.className}>
    <WagmiAppConfig>
      <Providers>
        {children}
      </Providers>
    </WagmiAppConfig>
    </body>
    </html>
  )
}
