import './globals.css'
import type {Metadata} from 'next'
import localFont from "next/font/local";
import Layout from "@/components/layout/Layout/Layout";
import {Provider} from "react-redux";
import {Providers} from "@/redux/provider";

const helvetica = localFont({
  src: [
    {
      path: './fonts/regular.woff',
      weight: '400',
      style: 'normal'
    },
    {
      path: './fonts/medium.woff',
      weight: '500',
      style: 'normal'
    },
    {
      path: './fonts/mediumItalic.woff',
      weight: '500',
      style: 'italic'
    },
    {
      path: './fonts/bold.woff',
      weight: '700',
      style: 'normal'
    },
  ]
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
                                     children,
                                   }: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <body className={helvetica.className}>
    <Providers>
      {children}
    </Providers>
    </body>
    </html>
  )
}
